name: Release

on:
  workflow_dispatch:
  push:
    branches: [master, alpha, beta, next]

permissions:
  id-token: write  # Required for OIDC token generation

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Get GitHub App Token
      id: token
      uses: SocialGouv/token-bureau@main
      with:
        token-bureau-url: https://token-bureau.fabrique.social.gouv.fr
        audience: socialgouv

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false

    # need to install deps for react-native-version
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Get yarn cache
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install
      run: yarn --frozen-lockfile --perfer-offline


    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        semantic_version: 17
        extra_plugins: |
          @semantic-release/changelog@5.0.1
          @semantic-release/git@9.0.0
      env:
        GITHUB_TOKEN: ${{ steps.token.outputs.token }}